### ISSUE TITLE
Task Editor Major Refactor

### ISSUE THREAD

**Issue by eukreign** [systori/systori#163]
- [ ] convert all linebreaks to `<br />` (so `\n` and others)
- [ ] update totals if LineItem is changed to `0,00` for price (so either qty, price or total) see #288 
- [x] support 5-level hirarchy in Projects
- [x] support to set the levels of hirarchy - so if only one level is needed, it should work too (f.e. only tasks without group)
- [x] handle long tasks codes better, now they grow into the task.name (f.e. 01.01.0001)
- [x] prevent orphan task instances
- [x] if alternate tasks are deleted make sure to either still display the taski instance name and description or delete it too, see #173
- [x] glorious LineItems Calculator, see #184 and https://goo.gl/emDjhQ
- [x] show save indicator on change
- [ ] support of task codes "in between" (f.e. 1.2.20 1.2.30 1.2.35 1.2.40)
- [ ] prevent unexpected deletion of elements
- [ ] reliable auto-complete on first element
- [ ] better highlighting of optional tasks
- [ ] better highlighting of alternate tasks
- [ ] improve scrolling when navigating witj arrow keys
- [x] supporting arrow keys up and down also within the task.description
- [ ] if a task gets inserted with autocomplete it should be copied including alternate tasks.
- [ ] support "task groups" like if you want a red roof there is always a roof and red color needed. A flat group within one hirarchy.
- [ ] Users should be able to change Order of TaskGroups/Tasks/LineItems
- [x] better matches for auto-complete searches (postgres full text search? With django 1.9 or 1.10)
- [ ] support Drag'n'Drop of Tasks
- [ ] hide/show LineItems, see #16
