### ISSUE TITLE
Timer Autopilot

### ISSUE THREAD

**Issue by eukreign** [systori/systori#233]
# User Story

As a worker using Systori, I would like to start my work timer in the morning and not have to take any further action for the rest of the day to have my hours recorded following the company prescribed breaks schedule and expected number of work hours.

I may also stop any running timers (work/break) and start an illness timer if I get sick on the job and leave in which case I expect that the timer will automatically stop after I have 8 hrs of billable time for the day (work hrs first part of day + illness hrs).
# Implementation Details

Phase 1:
- [ ] Autopilot code gets executed once a minute looping over all running timers.
- [ ] If it's currently time for a break, stop all running timers (mark as stopped by autopilot).
- [ ] If it's currently time for end of break, find all workers that: A) have no running timer currently, B) have a timer stopped today by autopilot; then start a new timer for this worker (mark as started by autopilot).
- [ ] For each running timer, check if total hours worked+'other billable leave' is 8 hrs, stop the timer (mark as stopped by autopilot).
- [ ] Make sure all recorded timer duration in seconds are multiples of 36. Always round up to nearest multiple of 36.
- [ ] no geolocation when autopilot starts or stops a Timer
- [ ] autopilot times are - 09:00 stop 9:30 start 12:30 stop 13:00 start 16:30 stop (3 Timers per day)

Phase 2:
- [ ] Show a message in the field app, 1 hour before break start, offering user to skip the upcoming timer break. Message may read something like with a button below it: "In 57 minutes your work timer will automatically pause for break. [Cancel Automatic Break]"
- [ ] Skips automatic break if worker has opted to do so.
